### ISSUE TITLE
e2e tests won't run locally due to missing selenium config

### ISSUE THREAD

**Issue by joerayme** [ahmednuaman/radian#31]
Running `grunt test` doesn't fully complete when running locally because selenium hasn't been set up:

```
Running "exec:e2e" (exec) task
Starting selenium standalone server...
>>
>> /usr/local/share/npm/lib/node_modules/protractor/lib/runner.js:187
>> throw new Error('Unable to start selenium. ' +
>> ^
>> Error: Unable to start selenium. You must specify either a seleniumAddress, seleniumServerJar, or saucelabs account, or use webdriver-manager.
>>   at setUpSelenium (/usr/local/share/npm/lib/node_modules/protractor/lib/runner.js:187:15)
>>   at Object.runOnce (/usr/local/share/npm/lib/node_modules/protractor/lib/runner.js:397:10)
>>   at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/protractor/lib/cli.js:102:8)
>>   at Module._compile (module.js:456:26)
>>   at Object.Module._extensions..js (module.js:474:10)
>>   at Module.load (module.js:356:32)
>>   at Function.Module._load (module.js:312:12)
>>   at Function.Module.runMain (module.js:497:10)
>>   at startup (node.js:119:16)
>>   at node.js:901:3
>> Exited with code: 8.
Warning: Task "exec:e2e" failed. Use --force to continue.
```

Not sure the solution to this - docs, extra config or both?

**Comment by ahmednuaman** [comment]
Ah, so you need to install protractor, simply run:
`[sudo] npm install -g protractor`
Then you need to update the `webdriver-manager` by running:
`webdriver-manager update`

**Comment by joerayme** [comment]
Ah cool, I thought it might be as simple as that. I'll give it a go. Is the radian.io source on GitHub so I can do a PR to add the testing info?

Great project by the way!

**Comment by ahmednuaman** [comment]
Yep, this is the repo with the content. Feel free to add those instructions to one of the `jade` content pages and I'll have a look.
